### PR TITLE
Issue 3179

### PR DESCRIPTION
**Pull request by rjschill87**
Implementing Mike's suggested fix of calculating the correct total for bundle purchaseableType.

### CODE REVIEW

**Review by chrisvariety — APPROVED** [review]
Can we add a test for this in `test.js` ? & bump version number! You can run `make` to run tests.

**Comment by rjschill87** [comment]
Test added and version number bumped!

**Review by chrisvariety — APPROVED** [review]
LGTM

**Review by mdeltito — APPROVED** [review]
👍 LGTM

**Pull request merged**
