### PR TITLE
V6

### PR DESCRIPTION
**Pull request by haddadnj**
Pull V6 into main trunk

### CODE REVIEW

**Comment by haddadnj** [comment]
Closing since this has drifted further

**Comment by nate-gehringer** [comment]
> Closing since this has drifted further

@haddadnj @chrisvariety Seems the `v6` branch had the latest code for this package – could you clarify why this branch was deleted / pull request was not merged? @damon-kasner-ti needs to update this package for ti#10981 and is not sure from where to base his work.

**Comment by chrisvariety** [comment]
@nate-gehringer I'll defer to @haddadnj on that for sure. My gut would say to base from `master` (which we should rename to `main`)

**Comment by haddadnj** [comment]
@nate-gehringer @damon-kasner-ti – yup the move here would be to use the main branch, if we _do_ need the `v6` changes then we'll need to merge them into `main` which is what this PR was intended to do facilitate. I'm not sure why `v6` never made it into the main branch to begin with though

**Pull request closed without merging**
